import { ServiceCategory, ServiceSubCategory, ServiceItem } from '../types';

export interface RecommendedItem {
  id: string;
  image: string;
  title: string;
  rating: string;
  discount?: string;
  price: string;
}

export const MOCK_RECOMMENDED: { title: string; categoryId: string; items: RecommendedItem[] }[] = [
  {
    title: 'Massage for Men',
    categoryId: 'cat-massage',
    items: [
      {
        id: 'rec-massage-1',
        image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?q=80&w=300',
        title: 'Quick Comfort Therapy',
        rating: '4.82',
        discount: '17% OFF',
        price: 'UGX   999',
      },
      {
        id: 'rec-massage-2',
        image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=300',
        title: 'Swedish Full Body Massage',
        rating: '4.90',
        discount: '25% OFF',
        price: 'UGX  699',
      },
      {
        id: 'rec-massage-3',
        image: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?q=80&w=300',
        title: 'Deep Tissue Massage',
        rating: '4.85',
        discount: '20% OFF',
        price: 'UGX  899',
      },
      {
        id: 'rec-massage-4',
        image: 'https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?q=80&w=300',
        title: 'Reflexology Foot Massage',
        rating: '4.72',
        discount: '15% OFF',
        price: 'UGX  399',
      },
    ],
  },
  {
    title: 'Popular Repairs',
    categoryId: 'cat-elec',
    items: [
      {
        id: 'rec-repair-1',
        image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=300',
        title: 'Switchboard Repair',
        rating: '4.80',
        discount: '10% OFF',
        price: 'UGX  99',
      },
      {
        id: 'rec-repair-2',
        image: 'https://images.unsplash.com/photo-1585123334904-845d60e97b29?q=80&w=300',
        title: 'Fan Installation',
        rating: '4.78',
        discount: '20% OFF',
        price: 'UGX  149',
      },
      {
        id: 'rec-repair-3',
        image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?q=80&w=300',
        title: 'Leaking Pipe Repair',
        rating: '4.70',
        discount: '15% OFF',
        price: 'UGX  179',
      },
      {
        id: 'rec-repair-4',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?q=80&w=300',
        title: 'Inverter Installation',
        rating: '4.83',
        discount: '5% OFF',
        price: 'UGX 499',
      },
    ],
  },
  {
    title: 'Cleaning Services',
    categoryId: 'cat-cleaning',
    items: [
      {
        id: 'rec-clean-1',
        image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=300',
        title: '1 BHK Deep Cleaning',
        rating: '4.70',
        discount: '30% OFF',
        price: 'UGX 1,499',
      },
      {
        id: 'rec-clean-2',
        image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=300',
        title: 'Sofa Upholstery Cleaning',
        rating: '4.65',
        discount: '20% OFF',
        price: 'UGX 599',
      },
      {
        id: 'rec-clean-3',
        image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=300',
        title: 'Bathroom Scrub & Polish',
        rating: '4.58',
        discount: '15% OFF',
        price: 'UGX 399',
      },
      {
        id: 'rec-clean-4',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=300',
        title: 'Kitchen Grease Cleaning',
        rating: '4.62',
        discount: '25% OFF',
        price: 'UGX 499',
      },
    ],
  },
];

export const MOCK_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat-elec',
    name: 'Electrician',
    bannerImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=600',
    rating: 4.8,
    totalBookings: '2.3 M bookings',
    hasOffers: true,
  },
  {
    id: 'cat-massage',
    name: 'Massage for Men',
    bannerImage: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?q=80&w=600',
    rating: 4.9,
    totalBookings: '1.2 M bookings',
  },
  {
    id: 'cat-plumber',
    name: 'Plumber',
    bannerImage: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?q=80&w=600',
    rating: 4.7,
    totalBookings: '1.8 M bookings',
    hasOffers: true,
  },
  {
    id: 'cat-painter',
    name: 'Painter',
    bannerImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=600',
    rating: 4.6,
    totalBookings: '980 K bookings',
  },
  {
    id: 'cat-cleaning',
    name: 'Cleaning',
    bannerImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=600',
    rating: 4.7,
    totalBookings: '3.1 M bookings',
    hasOffers: true,
  },
  {
    id: 'cat-ac',
    name: 'AC Service',
    bannerImage: 'https://images.unsplash.com/photo-1585777724706-2f0e1bfc1e3e?q=80&w=600',
    rating: 4.8,
    totalBookings: '1.5 M bookings',
    hasOffers: true,
  },
  {
    id: 'cat-carpentry',
    name: 'Carpentry',
    bannerImage: 'https://images.unsplash.com/photo-1611486212557-88be5ff6f941?q=80&w=600',
    rating: 4.6,
    totalBookings: '720 K bookings',
  },
  {
    id: 'cat-pest',
    name: 'Pest Control',
    bannerImage: 'https://images.unsplash.com/photo-1632935318677-4721c7ae52ec?q=80&w=600',
    rating: 4.5,
    totalBookings: '650 K bookings',
    hasOffers: true,
  },
];

export const MOCK_SUBCATEGORIES: ServiceSubCategory[] = [
  // Electrician
  { id: 'sub-socket', categoryId: 'cat-elec', name: 'Switch & socket', icon: 'power' },
  { id: 'sub-fan', categoryId: 'cat-elec', name: 'Fan', icon: 'wind' },
  { id: 'sub-wiring', categoryId: 'cat-elec', name: 'Wiring', icon: 'git-commit' },
  { id: 'sub-inverter', categoryId: 'cat-elec', name: 'Inverter', icon: 'battery-charging' },
  // Massage
  { id: 'sub-fullbody', categoryId: 'cat-massage', name: 'Full Body', icon: 'body' },
  { id: 'sub-foot', categoryId: 'cat-massage', name: 'Foot Massage', icon: 'accessibility' },
  // Plumber
  { id: 'sub-pipe', categoryId: 'cat-plumber', name: 'Pipe Repair', icon: 'water' },
  { id: 'sub-tap', categoryId: 'cat-plumber', name: 'Tap Installation', icon: 'construct' },
  { id: 'sub-drain', categoryId: 'cat-plumber', name: 'Drain Cleaning', icon: 'trash-bin' },
  // Painter
  { id: 'sub-wall', categoryId: 'cat-painter', name: 'Wall Painting', icon: 'color-palette' },
  { id: 'sub-texture', categoryId: 'cat-painter', name: 'Texture Paint', icon: 'brush' },
  { id: 'sub-waterproof', categoryId: 'cat-painter', name: 'Waterproofing', icon: 'rainy' },
  // Cleaning
  { id: 'sub-deepclean', categoryId: 'cat-cleaning', name: 'Deep Cleaning', icon: 'sparkles' },
  { id: 'sub-bathroom', categoryId: 'cat-cleaning', name: 'Bathroom', icon: 'water' },
  { id: 'sub-kitchen', categoryId: 'cat-cleaning', name: 'Kitchen', icon: 'flame' },
  // AC
  { id: 'sub-acrepair', categoryId: 'cat-ac', name: 'AC Repair', icon: 'thermometer' },
  { id: 'sub-acinstall', categoryId: 'cat-ac', name: 'AC Installation', icon: 'add-circle' },
  { id: 'sub-acgas', categoryId: 'cat-ac', name: 'Gas Refill', icon: 'leaf' },
  // Carpentry
  { id: 'sub-furniture', categoryId: 'cat-carpentry', name: 'Furniture Assembly', icon: 'hammer' },
  { id: 'sub-door', categoryId: 'cat-carpentry', name: 'Door Repair', icon: 'lock-closed' },
  { id: 'sub-cabinet', categoryId: 'cat-carpentry', name: 'Cabinet Making', icon: 'grid' },
  // Pest Control
  { id: 'sub-cockroach', categoryId: 'cat-pest', name: 'Cockroach Control', icon: 'bug' },
  { id: 'sub-termite', categoryId: 'cat-pest', name: 'Termite Control', icon: 'flask' },
  { id: 'sub-mosquito', categoryId: 'cat-pest', name: 'Mosquito Control', icon: 'fitness' },
];

export const MOCK_SERVICES: ServiceItem[] = [
  // Electrician - Switch & socket
  {
    id: 'srv-socket-1',
    subCategoryId: 'sub-socket',
    name: 'Switchboard repair',
    rating: 4.8,
    reviewsCount: '(3.1K reviews)',
    price: 99,
    durationMinutes: 30,
    descriptionPoints: [
      'Diagnosis of faulty switchboard',
      'Replacement of damaged switches',
      'Wiring check & safety test',
    ],
    image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=300',
  },
  {
    id: 'srv-socket-2',
    subCategoryId: 'sub-socket',
    name: 'New socket installation',
    rating: 4.7,
    reviewsCount: '(1.8K reviews)',
    price: 199,
    durationMinutes: 45,
    descriptionPoints: [
      'Installation of modular socket',
      'Concealed wiring connection',
      'Safety testing with multimeter',
    ],
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=300',
  },
  // Electrician - Fan
  {
    id: 'srv-fan-1',
    subCategoryId: 'sub-fan',
    name: 'Fan installation',
    rating: 4.8,
    reviewsCount: '(4.2K reviews)',
    price: 149,
    durationMinutes: 45,
    descriptionPoints: [
      'Installation of ceiling/wall fan',
      'Secure mounting & balancing',
      'Remote/wiring setup included',
    ],
    image: 'https://images.unsplash.com/photo-1585123334904-845d60e97b29?q=80&w=300',
  },
  {
    id: 'srv-fan-2',
    subCategoryId: 'sub-fan',
    name: 'Fan repair & servicing',
    rating: 4.6,
    reviewsCount: '(2.0K reviews)',
    price: 119,
    durationMinutes: 40,
    descriptionPoints: [
      'Noise or wobble diagnosis',
      'Capacitor & regulator check',
      'Lubrication & balancing',
    ],
    image: 'https://images.unsplash.com/photo-1614416221712-5a6e87528c1b?q=80&w=300',
  },
  // Electrician - Wiring
  {
    id: 'srv-wire-1',
    subCategoryId: 'sub-wiring',
    name: 'Concealed wiring',
    rating: 4.7,
    reviewsCount: '(1.5K reviews)',
    price: 349,
    durationMinutes: 120,
    descriptionPoints: [
      'Channel cutting & wiring layout',
      'PVC conduit & copper wire',
      'MCB box connection & testing',
    ],
    image: 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?q=80&w=300',
  },
  {
    id: 'srv-wire-2',
    subCategoryId: 'sub-wiring',
    name: 'Open wiring fix',
    rating: 4.5,
    reviewsCount: '(890 reviews)',
    price: 179,
    durationMinutes: 60,
    descriptionPoints: [
      'Inspection of exposed wiring',
      'Replacement of damaged cables',
      'Insulation taping & securing',
    ],
    image: 'https://images.unsplash.com/photo-1617799890501-cf3f3f3f3f3f?q=80&w=300',
  },
  // Electrician - Inverter
  {
    id: 'srv-inv-1',
    subCategoryId: 'sub-inverter',
    name: 'Inverter installation',
    rating: 4.8,
    reviewsCount: '(2.4K reviews)',
    price: 499,
    durationMinutes: 90,
    descriptionPoints: [
      'Mounting inverter & battery rack',
      'Battery connection & earthing',
      'Load testing & changeover check',
    ],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?q=80&w=300',
  },
  // Massage - Full Body
  {
    id: 'srv-massage-1',
    subCategoryId: 'sub-fullbody',
    name: 'Swedish full body massage',
    rating: 4.9,
    reviewsCount: '(5.6K reviews)',
    price: 699,
    durationMinutes: 60,
    descriptionPoints: [
      'Long gliding strokes for relaxation',
      'Kneading of deep muscle layers',
      'Aromatherapy oil included',
    ],
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=300',
  },
  {
    id: 'srv-massage-2',
    subCategoryId: 'sub-fullbody',
    name: 'Deep tissue massage',
    rating: 4.8,
    reviewsCount: '(3.2K reviews)',
    price: 899,
    durationMinutes: 60,
    descriptionPoints: [
      'Targeted deep muscle pressure',
      'Relief from chronic tension',
      'Therapeutic stretching included',
    ],
    image: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?q=80&w=300',
  },
  // Massage - Foot
  {
    id: 'srv-foot-1',
    subCategoryId: 'sub-foot',
    name: 'Reflexology foot massage',
    rating: 4.7,
    reviewsCount: '(1.9K reviews)',
    price: 399,
    durationMinutes: 30,
    descriptionPoints: [
      'Pressure point stimulation',
      'Stress relief & improved circulation',
      'Warm oil & towel service',
    ],
    image: 'https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?q=80&w=300',
  },
  // Plumber - Pipe Repair
  {
    id: 'srv-pipe-1',
    subCategoryId: 'sub-pipe',
    name: 'Leaking pipe repair',
    rating: 4.7,
    reviewsCount: '(2.8K reviews)',
    price: 179,
    durationMinutes: 45,
    descriptionPoints: [
      'Leak detection & assessment',
      'Pipe joint repair or replacement',
      'Water flow restoration test',
    ],
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?q=80&w=300',
  },
  {
    id: 'srv-pipe-2',
    subCategoryId: 'sub-pipe',
    name: 'PVC pipe installation',
    rating: 4.6,
    reviewsCount: '(1.2K reviews)',
    price: 299,
    durationMinutes: 90,
    descriptionPoints: [
      'Measured cutting & fitting',
      'Solvent welding & joint sealing',
      'Pressure testing',
    ],
    image: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?q=80&w=300',
  },
  // Plumber - Tap Installation
  {
    id: 'srv-tap-1',
    subCategoryId: 'sub-tap',
    name: 'Tap replacement',
    rating: 4.7,
    reviewsCount: '(2.1K reviews)',
    price: 149,
    durationMinutes: 30,
    descriptionPoints: [
      'Removal of old tap',
      'Fitting new tap & washers',
      'Water leak check',
    ],
    image: 'https://images.unsplash.com/photo-1584990347449-a5fbbf0d3e1c?q=80&w=300',
  },
  {
    id: 'srv-tap-2',
    subCategoryId: 'sub-tap',
    name: 'Bathroom faucet install',
    rating: 4.5,
    reviewsCount: '(950 reviews)',
    price: 249,
    durationMinutes: 60,
    descriptionPoints: [
      'Wall-mount or deck-mount fitting',
      'Flexible hose connection',
      'Water pressure adjustment',
    ],
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=300',
  },
  // Plumber - Drain Cleaning
  {
    id: 'srv-drain-1',
    subCategoryId: 'sub-drain',
    name: 'Clogged drain cleaning',
    rating: 4.6,
    reviewsCount: '(1.7K reviews)',
    price: 199,
    durationMinutes: 45,
    descriptionPoints: [
      'Drain inspection with camera',
      'High-pressure jet cleaning',
      'Debris removal & flushing',
    ],
    image: 'https://images.unsplash.com/photo-1590650151155-0f6e0d8b5a81?q=80&w=300',
  },
  // Painter - Wall Painting
  {
    id: 'srv-wall-1',
    subCategoryId: 'sub-wall',
    name: 'Interior wall painting',
    rating: 4.6,
    reviewsCount: '(3.4K reviews)',
    price: 1999,
    durationMinutes: 240,
    descriptionPoints: [
      'One coat primer + two coat paint',
      'Putty filling for cracks',
      'Drop cloths & furniture covering',
    ],
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=300',
  },
  {
    id: 'srv-wall-2',
    subCategoryId: 'sub-wall',
    name: 'Ceiling painting',
    rating: 4.5,
    reviewsCount: '(1.1K reviews)',
    price: 1499,
    durationMinutes: 180,
    descriptionPoints: [
      'Ladder & scaffold setup',
      'Stain blocking primer',
      'Even roller finish coat',
    ],
    image: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?q=80&w=300',
  },
  // Painter - Texture Paint
  {
    id: 'srv-texture-1',
    subCategoryId: 'sub-texture',
    name: 'Roller texture finish',
    rating: 4.7,
    reviewsCount: '(890 reviews)',
    price: 2499,
    durationMinutes: 180,
    descriptionPoints: [
      'Special texture roller application',
      'Custom pattern design',
      'Durable acrylic finish',
    ],
    image: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?q=80&w=300',
  },
  // Painter - Waterproofing
  {
    id: 'srv-water-1',
    subCategoryId: 'sub-waterproof',
    name: 'Terrace waterproofing',
    rating: 4.5,
    reviewsCount: '(720 reviews)',
    price: 3999,
    durationMinutes: 300,
    descriptionPoints: [
      'Surface cleaning & crack filling',
      'Liquid membrane application',
      'UV protective top coat',
    ],
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=300',
  },
  // Cleaning - Deep Cleaning
  {
    id: 'srv-deep-1',
    subCategoryId: 'sub-deepclean',
    name: '1 BHK deep cleaning',
    rating: 4.7,
    reviewsCount: '(6.2K reviews)',
    price: 1499,
    durationMinutes: 180,
    descriptionPoints: [
      'All rooms dusting & vacuuming',
      'Kitchen & bathroom scrubbing',
      'Floor mopping & disinfection',
    ],
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=300',
  },
  {
    id: 'srv-deep-2',
    subCategoryId: 'sub-deepclean',
    name: 'Sofa & upholstery cleaning',
    rating: 4.6,
    reviewsCount: '(2.3K reviews)',
    price: 599,
    durationMinutes: 60,
    descriptionPoints: [
      'Shampoo & hot water extraction',
      'Stain removal treatment',
      'Deodorizing & sanitizing',
    ],
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=300',
  },
  // Cleaning - Bathroom
  {
    id: 'srv-bath-1',
    subCategoryId: 'sub-bathroom',
    name: 'Bathroom scrub & polish',
    rating: 4.5,
    reviewsCount: '(1.8K reviews)',
    price: 399,
    durationMinutes: 60,
    descriptionPoints: [
      'Tile & grout scrubbing',
      'Mirror & fixture shining',
      'Mold removal & sanitization',
    ],
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=300',
  },
  // Cleaning - Kitchen
  {
    id: 'srv-kitchen-1',
    subCategoryId: 'sub-kitchen',
    name: 'Kitchen grease cleaning',
    rating: 4.6,
    reviewsCount: '(2.0K reviews)',
    price: 499,
    durationMinutes: 90,
    descriptionPoints: [
      'Chimney & stove degreasing',
      'Counter & cabinet wipe-down',
      'Floor scrubbing & drain clean',
    ],
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=300',
  },
  // AC - Repair
  {
    id: 'srv-acrepair-1',
    subCategoryId: 'sub-acrepair',
    name: 'AC not cooling diagnosis',
    rating: 4.8,
    reviewsCount: '(4.5K reviews)',
    price: 199,
    durationMinutes: 45,
    descriptionPoints: [
      'Filter & coil inspection',
      'Gas pressure measurement',
      'Repair estimate provided',
    ],
    image: 'https://images.unsplash.com/photo-1585777724706-2f0e1bfc1e3e?q=80&w=300',
  },
  {
    id: 'srv-acrepair-2',
    subCategoryId: 'sub-acrepair',
    name: 'Compressor repair',
    rating: 4.7,
    reviewsCount: '(1.6K reviews)',
    price: 799,
    durationMinutes: 120,
    descriptionPoints: [
      'Compressor electrical check',
      'Capacitor & relay replacement',
      'Cooling performance test',
    ],
    image: 'https://images.unsplash.com/photo-1585777724706-2f0e1bfc1e3e?q=80&w=300',
  },
  // AC - Installation
  {
    id: 'srv-acinstall-1',
    subCategoryId: 'sub-acinstall',
    name: 'Split AC installation',
    rating: 4.8,
    reviewsCount: '(3.8K reviews)',
    price: 999,
    durationMinutes: 120,
    descriptionPoints: [
      'Indoor unit mounting',
      'Outdoor unit placement & piping',
      'Vacuum & gas charging',
    ],
    image: 'https://images.unsplash.com/photo-1585777724706-2f0e1bfc1e3e?q=80&w=300',
  },
  // AC - Gas Refill
  {
    id: 'srv-acgas-1',
    subCategoryId: 'sub-acgas',
    name: 'AC gas refill (R32)',
    rating: 4.7,
    reviewsCount: '(2.9K reviews)',
    price: 1499,
    durationMinutes: 60,
    descriptionPoints: [
      'Leak detection test',
      'Full gas refill with R32',
      'Cooling temperature check',
    ],
    image: 'https://images.unsplash.com/photo-1585777724706-2f0e1bfc1e3e?q=80&w=300',
  },
  // Carpentry - Furniture Assembly
  {
    id: 'srv-furniture-1',
    subCategoryId: 'sub-furniture',
    name: 'DIY furniture assembly',
    rating: 4.6,
    reviewsCount: '(2.5K reviews)',
    price: 299,
    durationMinutes: 60,
    descriptionPoints: [
      'Unboxing & parts check',
      'Screw & dowel assembly',
      'Leveling & stability test',
    ],
    image: 'https://images.unsplash.com/photo-1611486212557-88be5ff6f941?q=80&w=300',
  },
  // Carpentry - Door Repair
  {
    id: 'srv-door-1',
    subCategoryId: 'sub-door',
    name: 'Door hinge replacement',
    rating: 4.5,
    reviewsCount: '(980 reviews)',
    price: 199,
    durationMinutes: 45,
    descriptionPoints: [
      'Removal of old hinges',
      'Screwing new heavy-duty hinges',
      'Alignment & swing check',
    ],
    image: 'https://images.unsplash.com/photo-1534237710431-e2fc698436d0?q=80&w=300',
  },
  // Carpentry - Cabinet Making
  {
    id: 'srv-cabinet-1',
    subCategoryId: 'sub-cabinet',
    name: 'Custom cabinet installation',
    rating: 4.7,
    reviewsCount: '(620 reviews)',
    price: 2999,
    durationMinutes: 240,
    descriptionPoints: [
      'Measure & mark layout',
      'Panel cutting & joining',
      'Drawer fitting & hardware install',
    ],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?q=80&w=300',
  },
  // Pest Control - Cockroach
  {
    id: 'srv-cockroach-1',
    subCategoryId: 'sub-cockroach',
    name: 'Cockroach treatment (1 BHK)',
    rating: 4.5,
    reviewsCount: '(3.1K reviews)',
    price: 499,
    durationMinutes: 45,
    descriptionPoints: [
      'Gel bait application in kitchen',
      'Spray treatment in cracks',
      'Follow-up prevention tips',
    ],
    image: 'https://images.unsplash.com/photo-1632935318677-4721c7ae52ec?q=80&w=300',
  },
  // Pest Control - Termite
  {
    id: 'srv-termite-1',
    subCategoryId: 'sub-termite',
    name: 'Termite control (1 BHK)',
    rating: 4.4,
    reviewsCount: '(1.8K reviews)',
    price: 1299,
    durationMinutes: 120,
    descriptionPoints: [
      'Drill & inject soil treatment',
      'Wood barrier application',
      '6-month warranty included',
    ],
    image: 'https://images.unsplash.com/photo-1632935318677-4721c7ae52ec?q=80&w=300',
  },
  // Pest Control - Mosquito
  {
    id: 'srv-mosquito-1',
    subCategoryId: 'sub-mosquito',
    name: 'Mosquito fogging treatment',
    rating: 4.3,
    reviewsCount: '(1.2K reviews)',
    price: 699,
    durationMinutes: 60,
    descriptionPoints: [
      'Indoor & outdoor fogging',
      'Larvicide in stagnant water',
      'Effective for 4-6 weeks',
    ],
    image: 'https://images.unsplash.com/photo-1632935318677-4721c7ae52ec?q=80&w=300',
  },
];
